#1.yearly_item_spending_by_group.R

#This script:
#      - generates yearly spending and shares by group and items.

#Input:
#      -  processed UCC spending by group and items generated by the “ucc_spending_cleaning” function and saved into “processed/group_urban_name_level/CEX Spending”.

#Outputs:
#     US level:
#      -     "yearly_cex_ri.csv": yearly expenditures and shares per group x items from the CEX saved into “intermediate/US/group_urban_name_level”.



#1. Get yearly item spending by group at the US level:
get_yearly_item_spending <- function(group, urban_name = "urban") {
  spending_weights <- combine_ucc_xwalk(group, urban_name)
  ucc_spending <- spending_weights[[1]] 
  yearly_weights <- spending_weights[[2]]


  
  make_dir(paste0(sharing_intermediate_base_path, "US/"))
  intermediate_us_path <- paste0(sharing_intermediate_base_path, "US/", group, "_", urban_name, "_level/")
  make_dir(paste0(intermediate_us_path))
  
  # Yearly Spending
  yearly_item_spending <- ucc_spending[, .(
    tot_expend = sum(tot_expend * wgt),
    tot_expend_scaled = sum(expend_scaled * group_popwt * wgt)
  ), by = c(group, "ucc_source", "year", "item_code")]
  
  yearly_item_spending <- yearly_item_spending[yearly_weights, on = c(group, "ucc_source", "year")]
  yearly_item_spending <- yearly_item_spending[, .(
    expend = sum(tot_expend / group_popwt),
    expend_scaled = sum(tot_expend_scaled / group_popwt)
  ),
  by = c(group, "year", "item_code")
  ]
  
  yearly_cpi_spending <- yearly_item_spending[ri_names, on = .(item_code), nomatch = NULL]
  yearly_cpi_spending <- yearly_cpi_spending[item_code_cpi != ""]
  
  yearly_cpi_spending <- yearly_cpi_spending[, .(
    expend = sum(expend),
    expend_scaled = sum(expend_scaled)
  ), by = c(group, "item_code_cpi", "year")]
  
  # CPI Year is the year the expenditures will be used to calculate the price index
  yearly_cpi_spending[, cpi_yr := ifelse(year < 2021, year + (year %% 2) + 2, year + 2)]
  yearly_item_spending[, cpi_yr := ifelse(year < 2021, year + (year %% 2) + 2, year + 2)]
  
  yearly_item_spending[, share := expend / sum(expend), by = c(group, "year")]
  
  cpi_yr_spending <- yearly_cpi_spending[, .(
    expend = sum(expend),
    expend_scaled = sum(expend_scaled)
  ), by = c(group, "item_code_cpi", "cpi_yr")]
  
  cpi_yr_spending[, `:=`(
    share = expend / sum(expend),
    share_scaled = expend_scaled / sum(expend_scaled)
  ), by = c("cpi_yr", group)]
  
  # Get the percent of spending on an item that goes to a specific group
  item_group_shares <- cpi_yr_spending
  item_group_shares <- item_group_shares[, c(group, "cpi_yr", "item_code_cpi", "expend"), with = FALSE]
  
  all_items <- item_group_shares[, unique(item_code_cpi)]
  all_cpi_years <- c(seq(1982, 2000, 2), item_group_shares[, unique(cpi_yr)])
  all_groups <- item_group_shares[, unique(get(group))]
  item_group_panel <- CJ(all_items, all_cpi_years, all_groups)
  colnames(item_group_panel) <- c("item_code_cpi", "cpi_yr", group)
  
  item_group_shares <- item_group_shares[item_group_panel, on = c(group, "item_code_cpi", "cpi_yr")]
  item_group_shares[is.na(expend), expend := 0]
  
  item_group_shares[get(group) == 0, share := 1]
  item_group_shares[get(group) != 0, share := expend / sum(expend),
                    by = .(cpi_yr, item_code_cpi)
  ]
  
  item_group_shares[is.na(share) & get(group) != 0, share := 1 / .N, by = c("cpi_yr", "item_code_cpi")]
  item_group_shares[get(group) == 0, share := 1, by = c("cpi_yr", "item_code_cpi")]
  

  item_group_shares_2002 <- item_group_shares[cpi_yr == 2002, !"cpi_yr"]
  
  item_group_shares <- item_group_shares[item_group_shares_2002, on = c(group, "item_code_cpi")]
  
  item_group_shares[cpi_yr < 2002, share := i.share]
  item_group_shares <- item_group_shares[, !c("i.share", "expend", "i.expend")]
  
  fwrite(cpi_yr_spending, paste0(intermediate_us_path, "yearly_cex_ri.csv"))
}
